services:
    phlexible_tree.mediator.element:
        class: Phlexible\Bundle\TreeBundle\Mediator\ElementMediator
        arguments:
            - "@phlexible_element.element_service"
            - "@phlexible_tree.element_mediator.viewable_voter"
            - "@phlexible_tree.element_mediator.sluggable_voter"

    phlexible_tree.mediator:
        class: Phlexible\Bundle\TreeBundle\Mediator\Mediator
        arguments: [["@phlexible_tree.mediator.element"]]

    phlexible_tree.element_mediator.viewable_voter.default:
        class: Phlexible\Bundle\TreeBundle\Mediator\ViewableVoter

    phlexible_tree.element_mediator.sluggable_voter.default:
        class: Phlexible\Bundle\TreeBundle\Mediator\SluggableVoter
